SELECT * FROM EMPLOYEES;

--Execute failing query:
SELECT * FROM EMPLOYEES WHERE SALARY < AVG(SALARY);
--Execute a working query: 
SELECT * FROM EMPLOYEES WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

--Execute a failing query
SELECT EMP_ID, SALARY, MAX(SALARY) AS MAX_SALARY FROM EMPLOYEES;
--Execute a working query
SELECT EMP_ID, SALARY, (SELECT MAX(SALARY) AS MAX_SALARY FROM EMPLOYEES) FROM EMPLOYEES;

SELECT EMP_ID, F_NAME, L_NAME, JOB_ID, MANAGER_ID, DEP_ID FROM EMPLOYEES AS NONSENSITIVE;