-- STRING PATTERNS
SELECT F_NAME, L_NAME FROM EMPLOYEES WHERE ADDRESS LIKE '%Elgin,IL%';

SELECT F_NAME, L_NAME, B_Date FROM EMPLOYEES WHERE B_DATE LIKE '197%';

SELECT F_NAME, L_NAME, DEP_ID, SALARY 
FROM EMPLOYEES 
WHERE DEP_ID=5 AND SALARY BETWEEN 60000 AND 70000;

-- SORTING
SELECT * FROM EMPLOYEES ORDER BY DEP_ID;

SELECT * FROM EMPLOYEES ORDER BY DEP_ID DESC, L_NAME DESC;

SELECT D.DEP_NAME, E.F_NAME, E.L_NAME
FROM EMPLOYEES AS E, DEPARTMENTS AS D
WHERE E.DEP_ID = D.DEPT_ID_DEP
ORDER BY D.DEP_NAME, E.L_NAME DESC;

--GROUPING 
SELECT DEP_ID, COUNT(*) FROM EMPLOYEES GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*), AVG(SALARY) FROM EMPLOYEES GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES 
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES 
GROUP BY DEP_ID
ORDER BY AVG(SALARY);

SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES 
GROUP BY DEP_ID
HAVING count(*) < 4
ORDER BY AVG(SALARY);